version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
          
  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_margin
        tests:
          - accepted_values:
              values: ['0.15', '0.2', '0.22', '0.25', '0.28', '0.3']